## Fama-French Portfolio Weights - Most Recent Results

### Execution Summary

The Fama-French factor replication was successfully completed with the following results:

**Data Coverage:**
- Downloaded 242,216 rows of CRSP data (2020-2025)
- Downloaded 52,673 rows of Compustat data
- Final sample: 236,939 CRSP observations with valid returns and market cap
- 10,388 firm-year portfolio assignments across all years

**Portfolio Construction:**
- Sorting variables prepared for 10,388 firm-year observations
- **Most recent portfolios: 2024-07-01 sorting date**
  - Valid for period: **July 2024 - June 2025** (covers current date)
  - Number of stocks: **3,350**
  - Uses June 2024 market caps and December 2023 Compustat data
- Note: 2025-07-01 portfolios require June 2025 CRSP data, which is not yet available in WRDS (data typically lags by several months)

**Replication Quality (30-month evaluation period):**
All factors show excellent correlation with official Fama-French data:
- **SMB (Size):** R² = 0.993, β = 0.921
- **HML (Value):** R² = 0.961, β = 0.959
- **RMW (Profitability):** R² = 0.935, β = 0.851
- **CMA (Investment):** R² = 0.950, β = 0.933

Below we load and examine the most recent portfolio weights available.

In [1]:
import pandas as pd
import numpy as np

# Load the portfolio assignments
portfolios_all = pd.read_csv("fama_french_portfolios_all_years.csv", parse_dates=["sorting_date"])

In [2]:
# Check what sorting dates are available
print("Available sorting dates:")
print(portfolios_all["sorting_date"].unique())
print(f"\nMost recent sorting date: {portfolios_all['sorting_date'].max()}")

Available sorting dates:
<DatetimeArray>
['2022-07-01 00:00:00', '2023-07-01 00:00:00', '2024-07-01 00:00:00']
Length: 3, dtype: datetime64[ns]

Most recent sorting date: 2024-07-01 00:00:00

In [3]:
# Filter for the most recent sorting date
most_recent_date = portfolios_all["sorting_date"].max()
portfolios_current = portfolios_all[portfolios_all["sorting_date"] == most_recent_date].copy()

print(f"Portfolio assignments for {most_recent_date.strftime('%Y-%m-%d')}:")
print(f"Number of stocks: {len(portfolios_current)}")
print(f"\nSummary by portfolio:")

portfolios_current.groupby(
    ["portfolio_size", "portfolio_bm", "portfolio_op", "portfolio_inv"]
).size()

Portfolio assignments for 2024-07-01:
Number of stocks: 3350

Summary by portfolio:

portfolio_size  portfolio_bm  portfolio_op  portfolio_inv
1               1             1             1                229
                                            2                 68
                                            3                183
                              2             1                 16
                                            2                 49
                                            3                 69
                              3             1                 30
                                            2                 64
                                            3                 78
                2             1             1                212
                                            2                 68
                                            3                 93
                              2             1                 62
                                            2                150
                                            3                131
                              3             1                 28
                                            2                 58
                                            3                 81
                3             1             1                292
                                            2                 87
                                            3                 68
                              2             1                 57
                                            2                137
                                            3                 87
                              3             1                 18
                                            2                 20
                                            3                 20
2               1             1             1                 18
                                            2                 12
                                            3                 43
                              2             1                 16
                                            2                 19
                                            3                 41
                              3             1                 58
                                            2                 41
                                            3                 74
                2             1             1                 33
                                            2                 40
                                            3                 34
                              2             1                 44
                                            2                 72
                                            3                 55
                              3             1                 18
                                            2                 33
                                            3                 20
                3             1             1                 45
                                            2                 42
                                            3                 25
                              2             1                 31
                                            2                 52
                                            3                 21
                              3             1                  2
                                            2                  2
                                            3                  4
dtype: int64

In [4]:
# Display sample of the most recent portfolios
portfolios_current

,permno,sorting_date,portfolio_size,portfolio_bm,portfolio_op,portfolio_inv,exchange,size
7038,14636,2024-07-01,1,2,2,3,AMEX,39.50830
7039,14647,2024-07-01,1,2,1,1,NASDAQ,196.66034
7040,14650,2024-07-01,1,3,2,2,NASDAQ,199.56042
7041,14653,2024-07-01,1,2,2,3,NASDAQ,785.70048
7042,14663,2024-07-01,1,2,2,2,NASDAQ,179.14160
...,...,...,...,...,...,...,...,...
10383,87842,2024-07-01,2,2,1,2,NYSE,49913.72337
10384,87952,2024-07-01,2,3,1,2,NYSE,4231.67748
10385,88031,2024-07-01,2,1,2,3,NASDAQ,49119.83100
10386,88159,2024-07-01,2,2,1,1,NASDAQ,6408.93834
10387,88182,2024-07-01,2,2,3,3,NASDAQ,29354.34390

In [5]:
# Portfolio composition by exchange
print("Portfolio composition by exchange:")

portfolios_current.groupby("exchange").agg({"permno": "count", "size": "sum"}).rename(columns={"permno": "num_stocks", "size": "total_mktcap"})

Portfolio composition by exchange:

          num_stocks  total_mktcap
exchange
AMEX             126  2.592013e+04
NASDAQ          2074  2.541167e+07
NYSE            1150  2.364480e+07